# Form implementation generated from reading ui file '.\Configuration.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 304)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/gui_resources/MrWorldwide.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.logo = QtWidgets.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(10, 10, 171, 281))
        self.logo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.logo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/logo/gui_resources/Configuration.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(480, 270, 75, 23))
        self.closeButton.setObjectName("closeButton")
        self.applyButton = QtWidgets.QPushButton(Dialog)
        self.applyButton.setGeometry(QtCore.QRect(400, 270, 75, 23))
        self.applyButton.setObjectName("applyButton")
        self.apiMirror = QtWidgets.QLineEdit(Dialog)
        self.apiMirror.setGeometry(QtCore.QRect(310, 10, 241, 20))
        self.apiMirror.setObjectName("apiMirror")
        self.apiMirrorLabel = QtWidgets.QLabel(Dialog)
        self.apiMirrorLabel.setGeometry(QtCore.QRect(190, 10, 111, 20))
        self.apiMirrorLabel.setObjectName("apiMirrorLabel")
        self.defaultSourceLangBox = QtWidgets.QComboBox(Dialog)
        self.defaultSourceLangBox.setGeometry(QtCore.QRect(330, 40, 69, 22))
        self.defaultSourceLangBox.setObjectName("defaultSourceLangBox")
        self.defaultSourceLangLabel = QtWidgets.QLabel(Dialog)
        self.defaultSourceLangLabel.setGeometry(QtCore.QRect(190, 40, 131, 21))
        self.defaultSourceLangLabel.setObjectName("defaultSourceLangLabel")
        self.defaultTargetLangLabel = QtWidgets.QLabel(Dialog)
        self.defaultTargetLangLabel.setGeometry(QtCore.QRect(190, 70, 131, 21))
        self.defaultTargetLangLabel.setObjectName("defaultTargetLangLabel")
        self.defaultTargetLangBox = QtWidgets.QComboBox(Dialog)
        self.defaultTargetLangBox.setGeometry(QtCore.QRect(330, 70, 69, 22))
        self.defaultTargetLangBox.setObjectName("defaultTargetLangBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configuration - Mr. Worldwide"))
        self.closeButton.setText(_translate("Dialog", "Close"))
        self.applyButton.setText(_translate("Dialog", "Apply"))
        self.apiMirror.setText(_translate("Dialog", "https://translate.astian.org/translate"))
        self.apiMirrorLabel.setText(_translate("Dialog", "LibreTranslate Mirror"))
        self.defaultSourceLangLabel.setText(_translate("Dialog", "Default Source Language"))
        self.defaultTargetLangLabel.setText(_translate("Dialog", "Default Target Language"))
